---
title: "Did COVID-19 Induce A Strenuous Effect on the 311 Non-Emergency Services System?"
output: github_document
---

```{r library, warning=FALSE, message = FALSE}
#load library
library(dplyr)
library(reshape2)
library(openxlsx)
library(car)
library(ggplot2)
library(hrbrthemes)
library(viridis)
library(ggpattern)
library(plm)
library(haven)
library(texreg)
library(lfe)
#install.packages("devtools")
#library(devtools)
#install_github('arilamstein/choroplethrZip@v1.3.0')
library(choroplethrZip)

#load 311 data 
load("kcmo2019_2020.rdata")

#load 911 data
dat911 = read.csv("kcmo 911 volume - data.csv")

#All Employees: Government: Local Government in Missouri (SMS29000009093000001)
datgov = read.csv("SMU29281409093000001SA.csv")
names(datgov) = c("datebls","empgov")
datgov$year = as.numeric(substr(datgov$datebls,1,4))
datgov$month = as.numeric(substr(datgov$datebls,6,7))
 
#covid cases by zipcode as of january 15, 2022
zip_covid = read.csv("COVID-19_Data_by_ZIP_Code.csv") 
zip_covid = zip_covid %>% dplyr::select(ZipCode,Cases,Total.Residents.Tested) %>% mutate(ZIP = ZipCode,rate = Cases/Total.Residents.Tested ) %>% dplyr::select(ZIP, rate)

```


```{r clean, warning=FALSE, message = FALSE}
# create year+month var
dat$date = dat$CREATEYR*100 +dat$CREATEMO

dat$date = as.Date(as.character(dat$date*100+1),"%Y%m%d")

# incomplete requests are imputed with 180 days (close date doen't exist)
#dat$DAYTOCLOSE[dat$DAYTOCLOSE==180] = NA

# create covid related calls 
dat = dat %>%
  mutate(
    
    covid = as.numeric(grepl("covid",tolower(description))|
                         grepl("corona",tolower(description))|
                         grepl("pandemic",tolower(description))|
                         grepl("virus",tolower(description))|
                         grepl("positive",tolower(description))
    ),
    
    mask = as.numeric(grepl("mask",tolower(description))|
                        grepl("face cover",tolower(description))|
                        grepl("ppe ",tolower(description))|
                        grepl("coverings",tolower(description))
    ),
    
    sdistance = as.numeric(grepl("social",tolower(description))|
                             grepl("distanc",tolower(description))|
                             grepl("6 feet",tolower(description))|
                             grepl("quarantine",tolower(description))|
                             grepl("stay at home",tolower(description))|
                             grepl("gathering",tolower(description))
    ),
    
    essential = as.numeric(grepl("essential",tolower(description))|
                             grepl("still open",tolower(description))|
                             grepl("open for business",tolower(description))|
                             grepl("open and operating",tolower(description))|
                             grepl("still operating",tolower(description))
    ), 
    
    allcovid = as.numeric((covid==1|mask==1|sdistance==1|essential==1) & season == "COVID-warm")
  )
```

supporting dataset

```{r}
# changes in request volume after covid by categories 
diff = dat %>% 
  filter(CATEGORY != "Data Not Available") %>%
  filter(CREATEMO %in% 3:8) %>%
  group_by(CREATEYR,CATEGORY) %>%
  count() %>% 
  dcast(CATEGORY~CREATEYR) %>% 
  mutate(diff = `2020`-`2019`,
         diff_pchg = `2020`/`2019` )
```


Despite the influx of covid-related calls, response time for public health and public safety are actually lower than the previous year  

```{r, fig.height=4, fig.width=8}
# plot request volume by categories
dat %>% 
  filter(CATEGORY != "Data Not Available") %>%
  filter(CATEGORY %in% c("Public Safety","Public Health")) %>%
  #filter(CREATEMO %in% 3:8) %>%
  group_by(CREATEYR,date,allcovid,CATEGORY) %>%
  count() %>% 
  left_join(diff)%>%
  mutate(CREATEYR = as.factor(CREATEYR),allcovid = as.factor(allcovid) )%>%
  ggplot(aes(x = date, y = n, fill = reorder(allcovid,-n)))+
  geom_col()+
  facet_wrap(~reorder(CATEGORY,-diff_pchg), scale = "free_y", ncol = 5)+
  scale_fill_manual(values = c("red3","dodgerblue4"))+
  scale_pattern_manual(values=c("stripe","none"))+
  scale_y_continuous(labels =scales::comma)+
  labs(y = "Requests Volume",
       x = "",
       fill = "Covid-Related"
       )+
  theme_bw()
```




```{r, fig.height=4, fig.width=8}
# plot response time by categories
dat %>% 
  filter(CATEGORY != "Data Not Available") %>%
  filter(CATEGORY %in% c("Public Safety","Public Health")) %>%
  #filter(CREATEMO %in% 3:8) %>%
  group_by(CREATEYR,date,allcovid,CATEGORY) %>%
  summarize(n = mean(DAYTOCLOSE,na.rm=T)) %>% 
  left_join(diff)%>%
  mutate(CREATEYR = as.factor(CREATEYR),allcovid = as.factor(allcovid) )%>%
  ggplot(aes(x = date, y = n, fill = reorder(allcovid,-n)))+
  geom_col(position = position_dodge())+
  facet_wrap(~reorder(CATEGORY,-diff_pchg), ncol = 5)+
  scale_fill_manual(values = c("red3","dodgerblue4"))+
  scale_pattern_manual(values=c("stripe","none"))+
  scale_y_continuous(labels =scales::comma)+
  labs(y = "Average Response Time",
       x = "",
       fill = "Covid-Related"
       )+
  coord_cartesian(ylim = c(0, 50)) +
  theme_bw()
```

```{r,fig.width=15,fig.height=8}
# plot request volume by categories
dat %>% 
  filter(CATEGORY != "Data Not Available") %>%
  filter(CREATEMO %in% 3:8) %>%
  group_by(CREATEYR,allcovid,CATEGORY) %>%
  count() %>% 
  left_join(diff)%>%
  mutate(CREATEYR = as.factor(CREATEYR),allcovid = as.factor(allcovid) )%>%
  ggplot(aes(x = CREATEYR, y = n,  group = reorder(CREATEYR,n), fill = CREATEYR))+
  geom_col_pattern(aes(pattern = reorder(allcovid,n)),#position = position_dodge(),
                   col="black",width = 0.8)+
  facet_wrap(~reorder(CATEGORY,-diff_pchg), scale = "free_y", ncol = 5)+
  scale_fill_manual(values = c("dodgerblue4","red3"))+
  scale_pattern_manual(values=c("stripe","none"))+
  scale_y_continuous(labels =scales::comma)+
  labs(y = "Requests Volume",
       x = "",
       fill = "Year",
       pattern = "Covid-Related"
       )+
  theme_bw()
```



```{r}
# plot response time by categories
dat %>% 
  filter(CATEGORY != "Data Not Available") %>%
  filter(CREATEMO %in% 3:8) %>%
  filter(allcovid==0) %>%
  left_join(diff)%>%
  mutate(CREATEYR = as.factor(CREATEYR))%>%
  group_by(CREATEYR, CATEGORY,diff_pchg) %>% 
  summarize(DAYTOCLOSE = mean(DAYTOCLOSE,na.rm=T)) %>% 
  dcast(CATEGORY+diff_pchg~CREATEYR) %>% mutate(
    dtc_chg = `2020`-`2019`
  ) %>%
  ggplot(aes(x = dtc_chg, y = reorder(CATEGORY,diff_pchg), fill = (diff_pchg) ))+
  geom_col(show.legend = FALSE)+
  xlim(c(-10,20))+
  #scale_fill_manual(values = c("red3","dodgerblue4"))+
  labs(x = "Change in Average Response Time",
       y = "",
  )+
  theme_bw()

```

Method 

Geographical variation 

```{r zipdata}
# yoy change in days to close
zip_dtc = dat %>% 
  #filter(CATEGORY %in% c("Public Safety","Public Health","Parks & Recreation")) %>%
  filter(CREATEMO %in% 3:8) %>%
  group_by(CREATEYR,CATEGORY, ZIP) %>%
  summarize(daytoclose = mean(DAYTOCLOSE,na.rm=T)) %>%
  dcast(CATEGORY + ZIP ~ CREATEYR) %>% 
  mutate(daytoclose_diff = `2020`-`2019`)%>% rename(daytoclose_2020 = `2020`,daytoclose_2019=`2019`)

# yoy change in volume
zip_n = dat %>% 
  #filter(CATEGORY %in% c("Public Safety","Public Health","Parks & Recreation")) %>%
  filter(CREATEMO %in% 3:8) %>%
  group_by(CREATEYR,CATEGORY, ZIP) %>%
  summarize(n = n()) %>%
  dcast(CATEGORY + ZIP ~ CREATEYR) %>% 
  mutate(n_diff = `2020`-`2019`,
         n_pchg = (`2020` / `2019`-1)*100)  %>% rename(n_2020 = `2020`,n_2019=`2019`)

# volume of covid-related of requests
zip_covid_311 = dat %>%
  group_by(ZIP) %>% 
  summarize(n = n(), n_allcovid = sum(allcovid)) %>% na.omit()

#merge data 
zip = zip_dtc %>% left_join(zip_n) %>%
  left_join(zip_covid) %>%
  left_join(zip_covid_311)
  
```

```{r zip_choropleth}

#list of zip to zoom in
zip_kcmo = unique(as.character(zip_covid_311$ZIP))

#zip code choropleth for 
zip_choropleth(zip_covid_311 %>% mutate(region = as.character(ZIP), value = n_allcovid), 
               zip_zoom = zip_kcmo,
               title      = "",
               legend     = "Volume of Covid-related Requests") + coord_map()   


```


```{r}
#scatterplot
dat %>% 
  #filter(CATEGORY %in% c("Public Safety","Public Health","Parks & Recreation")) %>%
  filter(CREATEMO %in% 3:8) %>%
  group_by(CREATEYR, ZIP) %>%
  summarize(daytoclose = mean(DAYTOCLOSE,na.rm=T)) %>%
  dcast(ZIP ~ CREATEYR) %>% 
  mutate(daytoclose_diff = `2020`-`2019`)%>% rename(daytoclose_2020 = `2020`,daytoclose_2019=`2019`) %>%
  left_join(zip_covid_311) %>% 
  ggplot(aes(y = daytoclose_diff, x = n_allcovid, size = n, col = ZIP))+
  geom_point()+
  geom_smooth(method=lm)+
  labs(
    y = "Change in Average Response Time",
    x = "Volume of Covid-related Requests"
  )+
  theme_bw()+
  theme(legend.position = "none")

#linear regression
summary(lm(daytoclose_diff~n_allcovid, data = dat %>% 
  #filter(CATEGORY %in% c("Public Safety","Public Health","Parks & Recreation")) %>%
  filter(CREATEMO %in% 3:8) %>%
  group_by(CREATEYR, ZIP) %>%
  summarize(daytoclose = mean(DAYTOCLOSE,na.rm=T)) %>%
  dcast(ZIP ~ CREATEYR) %>% 
  mutate(daytoclose_diff = `2020`-`2019`)%>% rename(daytoclose_2020 = `2020`,daytoclose_2019=`2019`) %>%
  left_join(zip_covid_311)
))
   
  
```

Difference in difference 

state and explain model


Regression results 

```{r}
# create data for request level reg
dat_reg = dat %>% 
  filter(allcovid==0) %>%
  left_join(zip_covid_311) %>% 
  mutate(after = as.numeric(season == "COVID-warm"),
         did = n_allcovid*after
         ) %>%  
  left_join(dat911, by=c("CREATEMO" = "month","CREATEYR" = "year")) %>%
  left_join(datgov, by=c("CREATEMO" = "month","CREATEYR" = "year"))


```

   
```{r}
#ols 
reg_ols = lm(data= dat_reg, DAYTOCLOSE~did + n_allcovid + after)
#fe: rate + after
reg_fe_a = (felm(data = dat_reg,DAYTOCLOSE~did|n_allcovid+after ))
#fe: rate + date(year-month)
reg_fe_b = (felm(data = dat_reg,DAYTOCLOSE~did|n_allcovid+factor(date) ))
#fe: rate + date(year-month)
reg_fe_c = (felm(data = dat_reg,DAYTOCLOSE~did|factor(NEIGH)+factor(date) ))

#combine reg 
screenreg(list(reg_ols, reg_fe_a, reg_fe_b,reg_fe_c), 
          omit.coef = "after|n_allcovid|Intercept|NEIGH", digits=4, 
          include.rsquared = FALSE, include.adjrs = FALSE, include.rmse = FALSE,
          custom.model.names = c("OLS", "FE period-zipcode", "FE date-zipcode","FE date-neighborhood"),
          custom.coef.names = "DiD effect"
          )
```


```{r}
#fe: rate + after
reg_fe_a = (felm(data = dat_reg,DAYTOCLOSE~did|n_allcovid+after ))
#fe: 911
reg_fe_b = (felm(data = dat_reg,DAYTOCLOSE~did+kcmo_fire_vol+kcmo_pd_vol|n_allcovid+after ))
#fe: gov employees
reg_fe_c = (felm(data = dat_reg,DAYTOCLOSE~did+empgov|n_allcovid+after ))
#fe: 911 + gov employees
reg_fe_d = (felm(data = dat_reg,DAYTOCLOSE~did+empgov+kcmo_fire_vol+kcmo_pd_vol|n_allcovid+after ))

#combine reg 
screenreg(list(reg_fe_a, reg_fe_b,reg_fe_c,reg_fe_d), 
          omit.coef = "after|n_allcovid|Intercept|NEIGH", digits=4, 
          include.rsquared = FALSE, include.adjrs = FALSE, include.rmse = FALSE,
          custom.model.names = c("(1)", "(2)","(3)","(4)"),
          custom.coef.names = c("DiD effect","911 Vol Fire Department","911 Vol Police Department","Local Government Employees")
          )
```

```{r}
#fe: 911 + gov employees
reg_fe_01 = (felm(data = dat_reg[dat_reg$CATEGORY=="Animals / Pets",],DAYTOCLOSE~did+empgov+kcmo_fire_vol+kcmo_pd_vol|n_allcovid+after ))
reg_fe_02 = (felm(data = dat_reg[dat_reg$CATEGORY=="Capital Projects",],DAYTOCLOSE~did+empgov+kcmo_fire_vol+kcmo_pd_vol|n_allcovid+after ))
reg_fe_03 = (felm(data = dat_reg[dat_reg$CATEGORY=="City Facilities",],DAYTOCLOSE~did+empgov+kcmo_fire_vol+kcmo_pd_vol|n_allcovid+after ))
reg_fe_04 = (felm(data = dat_reg[dat_reg$CATEGORY=="Government",],DAYTOCLOSE~did+empgov+kcmo_fire_vol+kcmo_pd_vol|n_allcovid+after ))
reg_fe_05 = (felm(data = dat_reg[dat_reg$CATEGORY=="Lights / Signals",],DAYTOCLOSE~did+empgov+kcmo_fire_vol+kcmo_pd_vol|n_allcovid+after ))
reg_fe_06 = (felm(data = dat_reg[dat_reg$CATEGORY=="Mowing / Weeds",],DAYTOCLOSE~did+empgov+kcmo_fire_vol+kcmo_pd_vol|n_allcovid+after ))
reg_fe_07 = (felm(data = dat_reg[dat_reg$CATEGORY=="Parks & Recreation",],DAYTOCLOSE~did+empgov+kcmo_fire_vol+kcmo_pd_vol|n_allcovid+after ))
reg_fe_08 = (felm(data = dat_reg[dat_reg$CATEGORY=="Property / Buildings / Construction",],DAYTOCLOSE~did+empgov+kcmo_fire_vol+kcmo_pd_vol|n_allcovid+after ))
reg_fe_09 = (felm(data = dat_reg[dat_reg$CATEGORY=="Public Health",],DAYTOCLOSE~did+empgov+kcmo_fire_vol+kcmo_pd_vol|n_allcovid+after ))
reg_fe_10 = (felm(data = dat_reg[dat_reg$CATEGORY=="Public Safety",],DAYTOCLOSE~did+empgov+kcmo_fire_vol+kcmo_pd_vol|n_allcovid+after ))
reg_fe_11 = (felm(data = dat_reg[dat_reg$CATEGORY=="Sidewalks / Curbs / Ditch",],DAYTOCLOSE~did+empgov+kcmo_fire_vol+kcmo_pd_vol|n_allcovid+after ))
reg_fe_12 = (felm(data = dat_reg[dat_reg$CATEGORY=="Signs",],DAYTOCLOSE~did+empgov+kcmo_fire_vol+kcmo_pd_vol|n_allcovid+after ))
reg_fe_13 = (felm(data = dat_reg[dat_reg$CATEGORY=="Storm Water / Sewer",],DAYTOCLOSE~did+empgov+kcmo_fire_vol+kcmo_pd_vol|n_allcovid+after ))
reg_fe_14 = (felm(data = dat_reg[dat_reg$CATEGORY=="Streets / Roadways / Alleys",],DAYTOCLOSE~did+empgov+kcmo_fire_vol+kcmo_pd_vol|n_allcovid+after ))
reg_fe_15 = (felm(data = dat_reg[dat_reg$CATEGORY=="Trash / Recycling",],DAYTOCLOSE~did+empgov+kcmo_fire_vol+kcmo_pd_vol|n_allcovid+after ))

#combine reg 
screenreg(list(reg_fe_01, reg_fe_02,reg_fe_03,reg_fe_04,reg_fe_05), 
          omit.coef = "after|n_allcovid|Intercept|NEIGH", digits=4, 
          include.rsquared = FALSE, include.adjrs = FALSE, include.rmse = FALSE,
          custom.model.names = c("Animals / Pets", "Capital Projects","City Facilities","Government","Lights / Signals"),
          custom.coef.names = c("DiD effect","911 Vol Fire Department","911 Vol Police Department","Local Government Employees")
          )

#combine reg 
screenreg(list(reg_fe_06, reg_fe_07,reg_fe_08,reg_fe_09,reg_fe_10), 
          omit.coef = "after|n_allcovid|Intercept|NEIGH", digits=4, 
          include.rsquared = FALSE, include.adjrs = FALSE, include.rmse = FALSE,
          custom.model.names = c("Mowing / Weeds", "Parks & Recreation","Property / Buildings / Construction","Public Health","Public Safety"),
          custom.coef.names = c("DiD effect","911 Vol Fire Department","911 Vol Police Department","Local Government Employees")
          )

#combine reg 
screenreg(list(reg_fe_11, reg_fe_12,reg_fe_13,reg_fe_14,reg_fe_15), 
          omit.coef = "after|n_allcovid|Intercept|NEIGH", digits=4, 
          include.rsquared = FALSE, include.adjrs = FALSE, include.rmse = FALSE,
          custom.model.names = c("Sidewalks / Curbs / Ditch", "Signs","Storm Water / Sewer","Streets / Roadways / Alleys","Trash / Recycling"),
          custom.coef.names = c("DiD effect","911 Vol Fire Department","911 Vol Police Department","Local Government Employees")
          )




```







