---
title: "Did COVID-19 Induce A Strenuous Effect on the 311 Non-Emergency Services System?"
output: github_document
---

```{r library, warning=FALSE, message = FALSE}
#load library
library(dplyr)
library(reshape2)
library(openxlsx)
library(car)
library(ggplot2)
library(hrbrthemes)
library(viridis)
library(ggpattern)
library(plm)
library(haven)
library(texreg)
library(lfe)
#install.packages("devtools")
#library(devtools)
#install_github('arilamstein/choroplethrZip@v1.3.0')
library(choroplethrZip)

#load 311 data 
load("kcmo2019_2020.rdata")

#load 911 data
dat911 = read.csv("kcmo 911 volume - data.csv")
 
#covid cases by zipcode as of january 15, 2022
zip_covid = read.csv("COVID-19_Data_by_ZIP_Code.csv") 
zip_covid = zip_covid %>% dplyr::select(ZipCode,Cases,Total.Residents.Tested) %>% mutate(ZIP = ZipCode,rate = Cases/Total.Residents.Tested ) %>% dplyr::select(ZIP, rate)

```


```{r clean, warning=FALSE, message = FALSE}
# create year+month var
dat$date = dat$CREATEYR*100 +dat$CREATEMO

dat$date = as.Date(as.character(dat$date*100+1),"%Y%m%d")

# create covid related calls 
dat = dat %>%
  mutate(
    
    covid = as.numeric(grepl("covid",tolower(description))|
                         grepl("corona",tolower(description))|
                         grepl("pandemic",tolower(description))|
                         grepl("virus",tolower(description))|
                         grepl("positive",tolower(description))
    ),
    
    mask = as.numeric(grepl("mask",tolower(description))|
                        grepl("face cover",tolower(description))|
                        grepl("ppe ",tolower(description))|
                        grepl("coverings",tolower(description))
    ),
    
    sdistance = as.numeric(grepl("social",tolower(description))|
                             grepl("distanc",tolower(description))|
                             grepl("6 feet",tolower(description))|
                             grepl("quarantine",tolower(description))|
                             grepl("stay at home",tolower(description))|
                             grepl("gathering",tolower(description))
    ),
    
    essential = as.numeric(grepl("essential",tolower(description))|
                             grepl("still open",tolower(description))|
                             grepl("open for business",tolower(description))|
                             grepl("open and operating",tolower(description))|
                             grepl("still operating",tolower(description))
    ), 
    
    allcovid = as.numeric((covid==1|mask==1|sdistance==1|essential==1) & season == "COVID-warm")
  )
```


Aggregate Trends

Call Volumes

```{r vol, warning=FALSE, message = FALSE,fig.width=8}
dat %>% 
  group_by(date,CREATEYR,CREATEMO,allcovid) %>%
  count() %>% 
  filter(CREATEMO %in% 3:8) %>%
  mutate(CREATEYR = as.factor(CREATEYR),allcovid = as.factor(allcovid) )%>%
  ggplot(aes(x = CREATEMO, y = n,  group = CREATEYR, fill = CREATEYR))+
  geom_col_pattern(aes(pattern = reorder(allcovid,n)),position = position_dodge(),
                   col="black",width = 0.8)+
  scale_fill_manual(values = c("dodgerblue4","green3"))+
  scale_pattern_manual(values=c("stripe","none"))+
  scale_x_continuous(breaks = 3:8)+
  scale_y_continuous(labels =scales::comma)+
  labs(y = "Requests Volume",
       x = "Month",
       fill = "Year",
       pattern = "Covid-Related"
       )+
  theme_bw()
```



Call Volumes by Request Types



```{r vol_cat, warning=FALSE, message = FALSE,fig.width=15,fig.height=8}
# changes in request volume after covid by categories 
diff = dat %>% 
  filter(CATEGORY != "Data Not Available") %>%
  filter(CREATEMO %in% 3:8) %>%
  group_by(CREATEYR,CATEGORY) %>%
  count() %>% 
  dcast(CATEGORY~CREATEYR) %>% 
  mutate(diff = `2020`-`2019`,
         diff_pchg = `2020`/`2019` )

# plot request volume by categories
dat %>% 
  filter(CATEGORY != "Data Not Available") %>%
  filter(CREATEMO %in% 3:8) %>%
  group_by(CREATEYR,allcovid,CATEGORY) %>%
  count() %>% 
  left_join(diff)%>%
  mutate(CREATEYR = as.factor(CREATEYR),allcovid = as.factor(allcovid) )%>%
  ggplot(aes(x = CREATEYR, y = n,  group = reorder(CREATEYR,n), fill = CREATEYR))+
  geom_col_pattern(aes(pattern = reorder(allcovid,n)),#position = position_dodge(),
                   col="black",width = 0.8)+
  facet_wrap(~reorder(CATEGORY,-diff_pchg), scale = "free_y", ncol = 5)+
  scale_fill_manual(values = c("dodgerblue4","green3"))+
  scale_pattern_manual(values=c("stripe","none"))+
  scale_y_continuous(labels =scales::comma)+
  labs(y = "Requests Volume",
       x = "",
       fill = "Year",
       pattern = "Covid-Related"
       )+
  theme_bw()
```
```{r rep_cat, warning=FALSE, message = FALSE,fig.height = 4,fig.width=6}
# plot response time by categories
dat %>% 
  filter(CATEGORY != "Data Not Available") %>%
  filter(CREATEMO %in% 3:8) %>%
  filter(allcovid==0) %>%
  left_join(diff)%>%
  mutate(CREATEYR = as.factor(CREATEYR))%>%
  group_by(CREATEYR, CATEGORY,diff_pchg) %>% summarize(DAYTOCLOSE = mean(DAYTOCLOSE)) %>% 
  dcast(CATEGORY+diff_pchg~CREATEYR) %>% mutate(
    dtc_chg = `2020`-`2019`
  ) %>%
  ggplot(aes(x = dtc_chg, y = reorder(CATEGORY,diff_pchg), fill = diff_pchg))+
  geom_col(show.legend = FALSE)+
  xlim(c(-10,25))+
  labs(x = "Change in Average Response Time",
       y = "",
  )+
  theme_bw()
```

Zip Code Variation 

```{r zipdata}
# yoy change in days to close
zip_dtc = dat %>% 
  #filter(CATEGORY %in% c("Public Safety","Public Health","Parks & Recreation")) %>%
  filter(CREATEMO %in% 3:8) %>%
  group_by(CREATEYR,CATEGORY, ZIP) %>%
  summarize(daytoclose = mean(DAYTOCLOSE,na.rm=T)) %>%
  dcast(CATEGORY + ZIP ~ CREATEYR) %>% 
  mutate(daytoclose_diff = `2020`-`2019`)%>% rename(daytoclose_2020 = `2020`,daytoclose_2019=`2019`)

# yoy change in volume
zip_n = dat %>% 
  #filter(CATEGORY %in% c("Public Safety","Public Health","Parks & Recreation")) %>%
  filter(CREATEMO %in% 3:8) %>%
  group_by(CREATEYR,CATEGORY, ZIP) %>%
  summarize(n = n()) %>%
  dcast(CATEGORY + ZIP ~ CREATEYR) %>% 
  mutate(n_diff = `2020`-`2019`,
         n_pchg = (`2020` / `2019`-1)*100)  %>% rename(n_2020 = `2020`,n_2019=`2019`)

# volume of covid-related of requests
zip_covid_311 = dat %>%
  group_by(ZIP) %>% 
  summarize(n = n(), n_allcovid = sum(allcovid)) %>% na.omit()

#merge data 
zip = zip_dtc %>% left_join(zip_n) %>%
  left_join(zip_covid) %>%
  left_join(zip_covid_311)
  
```

```{r zip_choropleth}

#list of zip to zoom in
zip_kcmo = unique(as.character(zip_covid_311$ZIP))

#zip code choropleth for 
zip_choropleth(zip_covid_311 %>% mutate(region = as.character(ZIP), value = n_allcovid), 
               zip_zoom = zip_kcmo,
               title      = "",
               legend     = "Volume of Covid-related Requests") + coord_map()   


```

```{r}
#scatterplot
dat %>% 
  #filter(CATEGORY %in% c("Public Safety","Public Health","Parks & Recreation")) %>%
  filter(CREATEMO %in% 3:8) %>%
  group_by(CREATEYR, ZIP) %>%
  summarize(daytoclose = mean(DAYTOCLOSE,na.rm=T)) %>%
  dcast(ZIP ~ CREATEYR) %>% 
  mutate(daytoclose_diff = `2020`-`2019`)%>% rename(daytoclose_2020 = `2020`,daytoclose_2019=`2019`) %>%
  left_join(zip_covid_311) %>% 
  ggplot(aes(y = daytoclose_diff, x = n_allcovid, size = n, col = ZIP))+
  geom_point()+
  geom_smooth(method=lm)+
  theme_bw()+
  theme(legend.position = "none")

#linear regression
summary(lm(daytoclose_diff~n_allcovid, data = dat %>% 
  #filter(CATEGORY %in% c("Public Safety","Public Health","Parks & Recreation")) %>%
  filter(CREATEMO %in% 3:8) %>%
  group_by(CREATEYR, ZIP) %>%
  summarize(daytoclose = mean(DAYTOCLOSE,na.rm=T)) %>%
  dcast(ZIP ~ CREATEYR) %>% 
  mutate(daytoclose_diff = `2020`-`2019`)%>% rename(daytoclose_2020 = `2020`,daytoclose_2019=`2019`) %>%
  left_join(zip_covid_311)
))
   
  
```

pretrends

```{r}
rank10 = zip_covid_311 %>% 
  mutate(group = cut(zip_covid_311$n_allcovid,breaks = quantile(zip_covid_311$n_allcovid,seq(0,1,0.2)),labels = FALSE,include.lowest = TRUE)) 

dat %>% left_join(rank10 ) %>% filter(group %in%c(1,5)) %>% 
  group_by(group,date) %>% 
  summarise(daytoclose = mean(DAYTOCLOSE,na.rm=T)) %>% 
  ggplot(aes(x = date, y = daytoclose, group = group, col = as.factor(group)))+
  geom_line(lwd= 1.5)+
  theme_bw()

```







Delay in response time for non-covid related requests




```{r zip_dtc, fig.height = 6,fig.width=8}
#scatterplot
zip %>%
  filter(CATEGORY != "Data Not Available") %>%
  ggplot(aes(y = daytoclose_diff, x = n_allcovid, size = n_2019, col = ZIP))+
  geom_point()+
  geom_smooth(method=lm)+
  facet_wrap(~CATEGORY, scale = "free", ncol=5)+
  theme_bw()+
  theme(legend.position = "none")
```

```{r}

# create data for request level reg
dat_reg = dat %>% 
  left_join(zip_covid) %>%
  left_join(zip_covid_311) %>% 
  mutate(after = as.numeric(season == "COVID-warm"),
         rate = rate*100) %>% 
  filter(allcovid==0) %>% 
  mutate(did = rate*after,
         did2 = n_allcovid*after)

```


```{r tab1}
#ols 
reg_ols = (lm(data= dat_reg, DAYTOCLOSE~did + rate + after))
#fe: rate + after
reg_fe_a = (felm(data = dat_reg,DAYTOCLOSE~did|rate+after ))
#fe: rate + date(year-month)
reg_fe_b = (felm(data = dat_reg,DAYTOCLOSE~did|rate+factor(date) ))

#combine reg 
screenreg(list(reg_ols, reg_fe_a, reg_fe_b), 
          omit.coef = "after|rate|Intercept", digits=4, 
          include.rsquared = FALSE, include.adjrs = FALSE, include.rmse = FALSE,
          custom.model.names = c("OLS", "FE period-rate", "FE date-rate"),
          custom.coef.names = "DiD effect"
          )

```


```{r tab2}
#ols 
reg_ols = (lm(data= dat_reg[dat_reg$CATEGORY == "Public Health",], DAYTOCLOSE~did + rate + after))
#fe: rate + after
reg_fe_a = (felm(data = dat_reg[dat_reg$CATEGORY == "Public Health",],DAYTOCLOSE~did|rate+after ))
#fe: rate + date(year-month)
reg_fe_b = (felm(data = dat_reg[dat_reg$CATEGORY == "Public Health",],DAYTOCLOSE~did|rate+factor(date) ))
#fe: nbh + date(year-month)
#reg_fe_c = (felm(data = dat_reg[dat_reg$CATEGORY == "Public Health",],DAYTOCLOSE~did|factor(NEIGH)+factor(date) ))


#combine reg 
screenreg(list(reg_ols, reg_fe_a, reg_fe_b), 
          omit.coef = "after|rate|Intercept", digits=4, 
          include.rsquared = FALSE, include.adjrs = FALSE, include.rmse = FALSE,
          custom.model.names = c("OLS", "FE period-rate", "FE date-rate"),
          custom.coef.names = "DiD effect"
          )

```

```{r tab3}
#ols 
reg_ols = (lm(data= dat_reg[dat_reg$CATEGORY == "Public Safety",], DAYTOCLOSE~did + rate + after))
#fe: rate + after
reg_fe_a = (felm(data = dat_reg[dat_reg$CATEGORY == "Public Safety",],DAYTOCLOSE~did|rate+after ))
#fe: rate + date(year-month)
reg_fe_b = (felm(data = dat_reg[dat_reg$CATEGORY == "Public Safety",],DAYTOCLOSE~did|rate+factor(date) ))

#combine reg 
screenreg(list(reg_ols, reg_fe_a, reg_fe_b), 
          omit.coef = "after|rate|Intercept", digits=4, 
          include.rsquared = FALSE, include.adjrs = FALSE, include.rmse = FALSE,
          custom.model.names = c("OLS", "FE period-rate", "FE date-rate"),
          custom.coef.names = "DiD effect"
          )

```
```{r tab4}
#ols 
reg_ols = (lm(data= dat_reg[dat_reg$CATEGORY == "Parks & Recreation",], DAYTOCLOSE~did + rate + after))
#fe: rate + after
reg_fe_a = (felm(data = dat_reg[dat_reg$CATEGORY == "Parks & Recreation",],DAYTOCLOSE~did|rate+after ))
#fe: rate + date(year-month)
reg_fe_b = (felm(data = dat_reg[dat_reg$CATEGORY == "Parks & Recreation",],DAYTOCLOSE~did|rate+factor(date) ))

#combine reg 
screenreg(list(reg_ols, reg_fe_a, reg_fe_b), 
          omit.coef = "after|rate|Intercept", digits=4, 
          include.rsquared = FALSE, include.adjrs = FALSE, include.rmse = FALSE,
          custom.model.names = c("OLS", "FE period-rate", "FE date-rate"),
          custom.coef.names = "DiD effect"
          )

```


```{r tab1a}
#ols 
reg_ols = (lm(data= dat_reg, DAYTOCLOSE~did2 + n_allcovid + after))
#fe: rate + after
reg_fe_a = (felm(data = dat_reg,DAYTOCLOSE~did2|n_allcovid+after ))
#fe: rate + date(year-month)
reg_fe_b = (felm(data = dat_reg,DAYTOCLOSE~did2|n_allcovid+factor(date) ))

#combine reg 
screenreg(list(reg_ols, reg_fe_a, reg_fe_b), 
          omit.coef = "after|n_allcovid|Intercept", digits=4, 
          include.rsquared = FALSE, include.adjrs = FALSE, include.rmse = FALSE,
          custom.model.names = c("OLS", "FE period-rate", "FE date-rate"),
          custom.coef.names = "DiD effect"
          )

```


```{r tab2a}
#ols 
reg_ols = (lm(data= dat_reg[dat_reg$CATEGORY == "Public Health",], DAYTOCLOSE~did2 + n_allcovid + after))
#fe: rate + after
reg_fe_a = (felm(data = dat_reg[dat_reg$CATEGORY == "Public Health",],DAYTOCLOSE~did2|n_allcovid+after ))
#fe: rate + date(year-month)
reg_fe_b = (felm(data = dat_reg[dat_reg$CATEGORY == "Public Health",],DAYTOCLOSE~did2|n_allcovid+factor(date) ))

#combine reg 
screenreg(list(reg_ols, reg_fe_a, reg_fe_b), 
          omit.coef = "after|n_allcovid|Intercept", digits=4, 
          include.rsquared = FALSE, include.adjrs = FALSE, include.rmse = FALSE,
          custom.model.names = c("OLS", "FE period-rate", "FE date-rate"),
          custom.coef.names = "DiD effect"
          )

```
```{r tab3a}
#ols 
reg_ols = (lm(data= dat_reg[dat_reg$CATEGORY == "Public Safety",], DAYTOCLOSE~did2 + n_allcovid + after))
#fe: rate + after
reg_fe_a = (felm(data = dat_reg[dat_reg$CATEGORY == "Public Safety",],DAYTOCLOSE~did2|n_allcovid+after ))
#fe: rate + date(year-month)
reg_fe_b = (felm(data = dat_reg[dat_reg$CATEGORY == "Public Safety",],DAYTOCLOSE~did2|n_allcovid+factor(date) ))

#combine reg 
screenreg(list(reg_ols, reg_fe_a, reg_fe_b), 
          omit.coef = "after|n_allcovid|Intercept", digits=4, 
          include.rsquared = FALSE, include.adjrs = FALSE, include.rmse = FALSE,
          custom.model.names = c("OLS", "FE period-rate", "FE date-rate"),
          custom.coef.names = "DiD effect"
          )

```
```{r tab4a}
#ols 
reg_ols = (lm(data= dat_reg[dat_reg$CATEGORY == "Parks & Recreation",], DAYTOCLOSE~did2 + n_allcovid + after))
#fe: rate + after
reg_fe_a = (felm(data = dat_reg[dat_reg$CATEGORY == "Parks & Recreation",], DAYTOCLOSE~did2|n_allcovid + after ))
#fe: rate + date(year-month)
reg_fe_b = (felm(data = dat_reg[dat_reg$CATEGORY == "Parks & Recreation",], DAYTOCLOSE~did2|n_allcovid + factor(date) ))

#combine reg 
screenreg(list(reg_ols, reg_fe_a, reg_fe_b), 
          omit.coef = "after|n_allcovid|Intercept", digits=4, 
          include.rsquared = FALSE, include.adjrs = FALSE, include.rmse = FALSE,
          custom.model.names = c("OLS", "FE period-rate", "FE date-rate"),
          custom.coef.names = "DiD effect"
          )

```

```{r tab5}
zip_reg = dat %>% 
  mutate(after = as.numeric(season == "COVID-warm")) %>% 
  filter(allcovid==0) %>% 
  #filter(CATEGORY == "Public Health") %>%
  group_by(date, ZIP, after) %>%
  summarise(DAYTOCLOSE = mean(DAYTOCLOSE,na.rm=T)) %>% 
  left_join(zip_covid) %>%
  left_join(zip_covid_311) %>%
  mutate(rate = rate*100,
         did = rate*after,
         did2 = n_allcovid*after)

#ols 
reg_ols = (lm(data= zip_reg, DAYTOCLOSE~did + rate + after))
#fe: rate + after
reg_fe_a = (felm(data = zip_reg,DAYTOCLOSE~did|rate+after ))
#fe: rate + date(year-month)
reg_fe_b = (felm(data = zip_reg,DAYTOCLOSE~did|rate+factor(date) ))

#combine reg 
screenreg(list(reg_ols, reg_fe_a, reg_fe_b), 
          omit.coef = "after|rate|Intercept", digits=4, 
          include.rsquared = FALSE, include.adjrs = FALSE, include.rmse = FALSE,
          custom.model.names = c("OLS", "FE period-rate", "FE date-rate"),
          custom.coef.names = "DiD effect"
          )

```

```{r tab6}
zip_reg = dat %>% 
  mutate(after = as.numeric(season == "COVID-warm")) %>% 
  filter(allcovid==0) %>% 
  filter(CATEGORY == "Public Health") %>%
  group_by(date, ZIP, after) %>%
  summarise(DAYTOCLOSE = mean(DAYTOCLOSE,na.rm=T)) %>% 
  left_join(zip_covid) %>%
  left_join(zip_covid_311) %>%
  mutate(rate = rate*100,
         did = rate*after,
         did2 = n_allcovid*after)

#ols 
reg_ols = (lm(data= zip_reg, DAYTOCLOSE~did + rate + after))
#fe: rate + after
reg_fe_a = (felm(data = zip_reg,DAYTOCLOSE~did|rate+after ))
#fe: rate + date(year-month)
reg_fe_b = (felm(data = zip_reg,DAYTOCLOSE~did|rate+factor(date) ))

#combine reg 
screenreg(list(reg_ols, reg_fe_a, reg_fe_b), 
          omit.coef = "after|rate|Intercept", digits=4, 
          include.rsquared = FALSE, include.adjrs = FALSE, include.rmse = FALSE,
          custom.model.names = c("OLS", "FE period-rate", "FE date-rate"),
          custom.coef.names = "DiD effect"
          )

```
```{r tab7}
zip_reg = dat %>% 
  mutate(after = as.numeric(season == "COVID-warm")) %>% 
  filter(allcovid==0) %>% 
  filter(CATEGORY == "Public Safety") %>%
  group_by(date, ZIP, after) %>%
  summarise(DAYTOCLOSE = mean(DAYTOCLOSE,na.rm=T)) %>% 
  left_join(zip_covid) %>%
  left_join(zip_covid_311) %>%
  mutate(rate = rate*100,
         did = rate*after,
         did2 = n_allcovid*after)

#ols 
reg_ols = (lm(data= zip_reg, DAYTOCLOSE~did + rate + after))
#fe: rate + after
reg_fe_a = (felm(data = zip_reg,DAYTOCLOSE~did|rate+after ))
#fe: rate + date(year-month)
reg_fe_b = (felm(data = zip_reg,DAYTOCLOSE~did|rate+factor(date) ))

#combine reg 
screenreg(list(reg_ols, reg_fe_a, reg_fe_b), 
          omit.coef = "after|rate|Intercept", digits=4, 
          include.rsquared = FALSE, include.adjrs = FALSE, include.rmse = FALSE,
          custom.model.names = c("OLS", "FE period-rate", "FE date-rate"),
          custom.coef.names = "DiD effect"
          )

```

```{r tab8}
zip_reg = dat %>% 
  mutate(after = as.numeric(season == "COVID-warm")) %>% 
  filter(allcovid==0) %>% 
  filter(CATEGORY == "Parks & Recreation") %>%
  group_by(date, ZIP, after) %>%
  summarise(DAYTOCLOSE = mean(DAYTOCLOSE,na.rm=T)) %>% 
  left_join(zip_covid) %>%
  left_join(zip_covid_311) %>%
  mutate(rate = rate*100,
         did = rate*after,
         did2 = n_allcovid*after)

#ols 
reg_ols = (lm(data= zip_reg, DAYTOCLOSE~did + rate + after))
#fe: rate + after
reg_fe_a = (felm(data = zip_reg,DAYTOCLOSE~did|rate+after ))
#fe: rate + date(year-month)
reg_fe_b = (felm(data = zip_reg,DAYTOCLOSE~did|rate+factor(date) ))

#combine reg 
screenreg(list(reg_ols, reg_fe_a, reg_fe_b), 
          omit.coef = "after|rate|Intercept", digits=4, 
          include.rsquared = FALSE, include.adjrs = FALSE, include.rmse = FALSE,
          custom.model.names = c("OLS", "FE period-rate", "FE date-rate"),
          custom.coef.names = "DiD effect"
          )

```

```{r tab5a}
zip_reg = dat %>% 
  mutate(after = as.numeric(season == "COVID-warm")) %>% 
  filter(allcovid==0) %>% 
  #filter(CATEGORY == "Public Health") %>%
  group_by(date, ZIP, after) %>%
  summarise(DAYTOCLOSE = mean(DAYTOCLOSE,na.rm=T)) %>% 
  left_join(zip_covid) %>%
  left_join(zip_covid_311) %>%
  mutate(rate = rate*100,
         did = rate*after,
         did2 = n_allcovid*after)

#ols 
reg_ols = (lm(data= zip_reg, DAYTOCLOSE~did2 + n_allcovid + after))
#fe: rate + after
reg_fe_a = (felm(data = zip_reg,DAYTOCLOSE~did2|n_allcovid+after ))
#fe: rate + date(year-month)
reg_fe_b = (felm(data = zip_reg,DAYTOCLOSE~did2|n_allcovid+factor(date) ))

#combine reg 
screenreg(list(reg_ols, reg_fe_a, reg_fe_b), 
          omit.coef = "after|n_allcovid|Intercept", digits=4, 
          include.rsquared = FALSE, include.adjrs = FALSE, include.rmse = FALSE,
          custom.model.names = c("OLS", "FE period-rate", "FE date-rate"),
          custom.coef.names = "DiD effect"
          )

```

```{r tab6a}
zip_reg = dat %>% 
  mutate(after = as.numeric(season == "COVID-warm")) %>% 
  filter(allcovid==0) %>% 
  filter(CATEGORY == "Public Health") %>%
  group_by(date, ZIP, after) %>%
  summarise(DAYTOCLOSE = mean(DAYTOCLOSE,na.rm=T)) %>% 
  left_join(zip_covid) %>%
  left_join(zip_covid_311) %>%
  mutate(rate = rate*100,
         did = rate*after,
         did2 = n_allcovid*after)

#ols 
reg_ols = (lm(data= zip_reg, DAYTOCLOSE~did2 + n_allcovid + after))
#fe: rate + after
reg_fe_a = (felm(data = zip_reg,DAYTOCLOSE~did2|n_allcovid+after ))
#fe: rate + date(year-month)
reg_fe_b = (felm(data = zip_reg,DAYTOCLOSE~did2|n_allcovid+factor(date) ))

#combine reg 
screenreg(list(reg_ols, reg_fe_a, reg_fe_b), 
          omit.coef = "after|n_allcovid|Intercept", digits=4, 
          include.rsquared = FALSE, include.adjrs = FALSE, include.rmse = FALSE,
          custom.model.names = c("OLS", "FE period-rate", "FE date-rate"),
          custom.coef.names = "DiD effect"
          )

```

```{r tab7a}
zip_reg = dat %>% 
  mutate(after = as.numeric(season == "COVID-warm")) %>% 
  filter(allcovid==0) %>% 
  filter(CATEGORY == "Public Safety") %>%
  group_by(date, ZIP, after) %>%
  summarise(DAYTOCLOSE = mean(DAYTOCLOSE,na.rm=T)) %>% 
  left_join(zip_covid) %>%
  left_join(zip_covid_311) %>%
  mutate(rate = rate*100,
         did = rate*after,
         did2 = n_allcovid*after)

#ols 
reg_ols = (lm(data= zip_reg, DAYTOCLOSE~did2 + n_allcovid + after))
#fe: rate + after
reg_fe_a = (felm(data = zip_reg,DAYTOCLOSE~did2|n_allcovid+after ))
#fe: rate + date(year-month)
reg_fe_b = (felm(data = zip_reg,DAYTOCLOSE~did2|n_allcovid+factor(date) ))

#combine reg 
screenreg(list(reg_ols, reg_fe_a, reg_fe_b), 
          omit.coef = "after|n_allcovid|Intercept", digits=4, 
          include.rsquared = FALSE, include.adjrs = FALSE, include.rmse = FALSE,
          custom.model.names = c("OLS", "FE period-rate", "FE date-rate"),
          custom.coef.names = "DiD effect"
          )

```

```{r tab8a}
zip_reg = dat %>% 
  mutate(after = as.numeric(season == "COVID-warm")) %>% 
  filter(allcovid==0) %>% 
  filter(CATEGORY == "Parks & Recreation") %>%
  group_by(date, ZIP, after) %>%
  summarise(DAYTOCLOSE = mean(DAYTOCLOSE,na.rm=T)) %>% 
  left_join(zip_covid) %>%
  left_join(zip_covid_311) %>%
  mutate(rate = rate*100,
         did = rate*after,
         did2 = n_allcovid*after)

#ols 
reg_ols = (lm(data= zip_reg, DAYTOCLOSE~did2 + n_allcovid + after))
#fe: rate + after
reg_fe_a = (felm(data = zip_reg,DAYTOCLOSE~did2|n_allcovid+after ))
#fe: rate + date(year-month)
reg_fe_b = (felm(data = zip_reg,DAYTOCLOSE~did2|n_allcovid+factor(date) ))

#combine reg 
screenreg(list(reg_ols, reg_fe_a, reg_fe_b), 
          omit.coef = "after|n_allcovid|Intercept", digits=4, 
          include.rsquared = FALSE, include.adjrs = FALSE, include.rmse = FALSE,
          custom.model.names = c("OLS", "FE period-rate", "FE date-rate"),
          custom.coef.names = "DiD effect"
          )

```









Discussion 

Categories vs Departments 

```{r cate_dept, fig.height=8,fig.width=8}
dat %>%
  filter(CATEGORY != "Data Not Available") %>%
  filter(CREATEMO %in% 3:8) %>%
  group_by(CATEGORY, DEPT) %>%
  count() %>%
  left_join(diff)%>%
  mutate(selected = CATEGORY %in% c("Public Health","Public Safety","Parks & Recreation"))%>%
  ggplot(aes(x = reorder(CATEGORY,-diff_pchg), y = DEPT, fill = n, col = selected))+
  geom_tile(lwd=1.5)+
  scale_x_discrete(guide = guide_axis(angle = 90))+
  scale_color_manual(values=c("white","red"))+
  labs(
    y = "Department",
    x = "Category",
    fill = "Request Volume",
    col = "Selected Catgories"
  )+
  theme_bw()
```

911 trends 
```{r vol911}

dat911 %>% 
  filter(month %in% 3:8) %>%
  mutate(year = as.factor(year)) %>%
  select(year, month, 
         kcmo_fire_vol,kcmo_fire_vol_911,kcmo_fire_vol_nonemergency,
         kcmo_pd_vol,kcmo_pd_vol_911,kcmo_pd_vol_nonemergency) %>%
  melt(id.vars=c("year","month")) %>%
  ggplot(aes(x = year, y = value, group = year, fill = year)) + 
  geom_boxplot(show.legend=FALSE)+
  facet_wrap(~variable,scale="free_y")+
  scale_fill_manual(values = c("dodgerblue4","green3"))+
  #scale_x_continuous(breaks = 3:8)+
  scale_y_continuous(labels =scales::comma)+
  labs(y = "911 Volume",
       x = "Month",
       fill = "Year"
       )+
  theme_bw()
```


```{r ringtime911}

dat911 %>% 
  filter(month %in% 3:8) %>%
  mutate(year = as.factor(year)) %>%
  select(year, month, 
         kcmo_fire_pct_answered_15s,kcmo_fire_pct_answered_20s,kcmo_fire_pct_answered_40s,
         kcmo_pd_pct_answered_15s,kcmo_pd_pct_answered_20s,kcmo_pd_pct_answered_40s) %>%
  melt(id.vars=c("year","month")) %>%
  ggplot(aes(x = year, y = value, group = year, fill = year)) + 
  geom_boxplot(show.legend=FALSE)+
  facet_wrap(~variable,scale="free_y")+
  scale_fill_manual(values = c("dodgerblue4","green3"))+
  labs(y = "911 Ringtime Range",
       x = "",
       fill = "Year"
       )+
  theme_bw()
```














